version: "3.8"

services:
  jenkins-blueocean:
    image: jenkins-blueocean:2.440.2-1
    restart: on-failure
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  jenkins:
    external: true
